# Generated by Django 5.0.7 on 2024-07-10 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testimonial",
            name="content",
            field=models.TextField(verbose_name="Testimonial content"),
        ),
        migrations.AlterField(
            model_name="testimonial",
            name="image",
            field=models.ImageField(
                upload_to="testimonials/", verbose_name="Avatar Image"
            ),
        ),
        migrations.AlterField(
            model_name="testimonial",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Full Name"),
        ),
    ]
