# Generated by Django 5.0.7 on 2024-07-10 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_testimonial_content_alter_testimonial_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="testimonial",
            name="profession",
            field=models.CharField(
                default="Doctor", max_length=255, verbose_name="Profession"
            ),
            preserve_default=False,
        ),
    ]
