# Generated by Django 5.0.6 on 2024-07-14 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_teammember"),
    ]

    operations = [
        migrations.CreateModel(
            name="BrandStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "happy_customers",
                    models.IntegerField(verbose_name="Happy Customers"),
                ),
                (
                    "projects_completed",
                    models.IntegerField(verbose_name="Projects Completed"),
                ),
                ("awards_won", models.IntegerField(verbose_name="Awards Won")),
                ("expert_workers", models.IntegerField(verbose_name="Expert Workers")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CarouselImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255, verbose_name="Image Title")),
                ("description", models.TextField(verbose_name="Image Description")),
                (
                    "image",
                    models.ImageField(
                        upload_to="carousel/", verbose_name="Carousel Image"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
